#!/usr/bin/env python3
"""Generate org-registry-derived regions from the single source of truth.

tools/registry/repos.json is the ONLY hand-edited list of org submodules. This
script regenerates everything that used to be duplicated by hand across the
coordination root:

  * MODULE.bazel        -- the bazel_dep + local_path_override block (no versions)
  * BUILD.bazel         -- the per-child native_gate test_suites + native_gates
  * README.md           -- the "Repository Model" table
  * repos.generated.sh  -- bash arrays sourced by the tools/bazel/*.sh contracts

Usage:
  python3 tools/registry/generate.py --check   # fail if any output is stale (CI)
  python3 tools/registry/generate.py --write    # rewrite the generated regions

Only files OWNED BY THE COORDINATION ROOT are written. The generator never
touches a submodule working tree (no child Package.swift / package.json / child
MODULE.bazel), preserving the invariant that public child repos build standalone.
"""

import argparse
import difflib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFEST = REPO_ROOT / "tools" / "registry" / "repos.json"


def load_repos():
    data = json.loads(MANIFEST.read_text())
    repos = data["repos"]
    bazel = [r for r in repos if r.get("bazel_module")]
    return repos, bazel


# --- region builders --------------------------------------------------------

def build_module_deps(bazel):
    deps = "\n".join(f'bazel_dep(name = "{r["module"]}")' for r in bazel)
    overrides = "\n\n".join(
        f'local_path_override(\n'
        f'    module_name = "{r["module"]}",\n'
        f'    path = "{r["name"]}",\n'
        f')'
        for r in bazel
    )
    return deps + "\n\n" + overrides


def build_native_gates(bazel):
    suites = "\n\n".join(
        f'test_suite(\n'
        f'    name = "{r["module"]}_native_gate",\n'
        f'    tests = ["@{r["module"]}//:native_gate"],\n'
        f')'
        for r in bazel
    )
    agg_tests = "\n".join(f'        ":{r["module"]}_native_gate",' for r in bazel)
    agg = (
        f'test_suite(\n'
        f'    name = "native_gates",\n'
        f'    tests = [\n'
        f'{agg_tests}\n'
        f'    ],\n'
        f')'
    )
    return suites + "\n\n" + agg


def build_readme_table(repos):
    header = (
        "| Path | GitHub repo | Native contract | Bazel module |\n"
        "| --- | --- | --- | --- |"
    )
    rows = []
    for r in repos:
        mod = f"`{r['module']}`" if r.get("bazel_module") else "—"
        rows.append(f"| `{r['name']}/` | `{r['github']}` | {r['native_contract']} | {mod} |")
    return header + "\n" + "\n".join(rows)


def build_generated_sh(repos, bazel):
    def arr(name, items):
        return name + "=(" + " ".join(f'"{x}"' for x in items) + ")"

    return "\n".join([
        "# GENERATED by tools/registry/generate.py from tools/registry/repos.json -- do not edit.",
        "# Sourced by the tools/bazel/*.sh contract scripts. bash 3.2 safe (indexed arrays only).",
        arr("BAZEL_MODULE_REPOS", [r["name"] for r in bazel]),
        arr("BAZEL_MODULE_NAMES", [r["module"] for r in bazel]),
        arr("BAZEL_MODULE_URLS", [r["url"] for r in bazel]),
        arr("ALL_SUBMODULE_REPOS", [r["name"] for r in repos]),
        arr("ALL_SUBMODULE_URLS", [r["url"] for r in repos]),
    ]) + "\n"


# --- marker region replacement ----------------------------------------------

def splice_region(path, tag, content):
    """Return the new text for `path` with the region between the tag markers
    replaced by `content`. Markers themselves are preserved."""
    start = f">>> GENERATED:{tag}"
    end = f"<<< GENERATED:{tag}"
    text = path.read_text()
    trailing_nl = text.endswith("\n")
    lines = text.split("\n")
    if trailing_nl and lines and lines[-1] == "":
        lines = lines[:-1]

    s = e = None
    for i, line in enumerate(lines):
        if start in line:
            s = i
        elif end in line:
            e = i
            break
    if s is None or e is None or e <= s:
        raise SystemExit(f"[generate] markers for '{tag}' not found in {path.relative_to(REPO_ROOT)}")

    new_lines = lines[: s + 1] + content.split("\n") + lines[e:]
    out = "\n".join(new_lines)
    return out + "\n" if trailing_nl else out


# --- targets ----------------------------------------------------------------

def planned_outputs():
    repos, bazel = load_repos()
    return [
        ("spliced", REPO_ROOT / "MODULE.bazel", "module-deps", build_module_deps(bazel)),
        ("spliced", REPO_ROOT / "BUILD.bazel", "native-gates", build_native_gates(bazel)),
        ("spliced", REPO_ROOT / "README.md", "repos-table", build_readme_table(repos)),
        ("whole", REPO_ROOT / "tools" / "registry" / "repos.generated.sh",
         None, build_generated_sh(repos, bazel)),
    ]


def render(kind, path, tag, content):
    if kind == "spliced":
        return splice_region(path, tag, content)
    return content


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--check", action="store_true", help="fail if any generated output is stale")
    g.add_argument("--write", action="store_true", help="rewrite the generated regions in place")
    args = ap.parse_args()

    stale = []
    for kind, path, tag, content in planned_outputs():
        want = render(kind, path, tag, content)
        have = path.read_text() if path.exists() else ""
        if want == have:
            continue
        if args.write:
            path.write_text(want)
            print(f"[generate] wrote {path.relative_to(REPO_ROOT)}")
        else:
            stale.append((path, have, want))

    if args.check:
        if stale:
            for path, have, want in stale:
                print(f"[generate] STALE: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
                diff = difflib.unified_diff(
                    have.splitlines(), want.splitlines(),
                    fromfile=f"a/{path.relative_to(REPO_ROOT)}",
                    tofile=f"b/{path.relative_to(REPO_ROOT)}",
                    lineterm="",
                )
                print("\n".join(diff), file=sys.stderr)
            print(
                "\n[generate] generated files are out of date with tools/registry/repos.json.\n"
                "  Run: python3 tools/registry/generate.py --write",
                file=sys.stderr,
            )
            return 1
        print("[generate] ok -- all generated regions match tools/registry/repos.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
