# GENERATED by tools/registry/generate.py from tools/registry/repos.json -- do not edit.
# Sourced by the tools/bazel/*.sh contract scripts. bash 3.2 safe (indexed arrays only).
BAZEL_MODULE_REPOS=("swift-tui" "swift-tui-swiftui" "swift-tui-web" "swift-tui-examples" "swift-tui-site" "swift-tui-android")
BAZEL_MODULE_NAMES=("swift_tui" "swift_tui_swiftui" "swift_tui_web" "swift_tui_examples" "swift_tui_site" "swift_tui_android")
BAZEL_MODULE_URLS=("git@github.com:SwiftTUI/swift-tui.git" "git@github.com:SwiftTUI/swift-tui-swiftui.git" "git@github.com:SwiftTUI/swift-tui-web.git" "git@github.com:SwiftTUI/swift-tui-examples.git" "git@github.com:SwiftTUI/swift-tui-site.git" "git@github.com:SwiftTUI/swift-tui-android.git")
ALL_SUBMODULE_REPOS=("swift-tui" "swift-tui-swiftui" "swift-tui-web" "swift-tui-examples" "swift-tui-site" "swift-tui-android" "github")
ALL_SUBMODULE_URLS=("git@github.com:SwiftTUI/swift-tui.git" "git@github.com:SwiftTUI/swift-tui-swiftui.git" "git@github.com:SwiftTUI/swift-tui-web.git" "git@github.com:SwiftTUI/swift-tui-examples.git" "git@github.com:SwiftTUI/swift-tui-site.git" "git@github.com:SwiftTUI/swift-tui-android.git" "git@github.com:SwiftTUI/.github.git")
