#!/usr/bin/env python3
"""True-pixel visual tier for the SwiftUI-vs-SwiftTUI layout sweep.

Pairs the two engines' offscreen pixel renders by `id` and assembles a
SwiftUI | SwiftTUI side-by-side contact sheet, ranked by the geometry
content-extent IoU from `diff.py` (the meaningful discrepancy signal).

Why no pixel-diff metric: DSSIM/AE between these two engines SATURATE — SwiftUI
renders proportional ink at square (10x10) cells, SwiftTUI renders monospace
glyphs at tall (~7x14) cells, so forcing them onto a common canvas makes every
entry ~maximally different and the heatmap is ~all-red. That was tested and
discarded; the side-by-side visual + the geometry IoU are the real signals.

Coordination tooling (org root). Reads ephemeral renders from /tmp/layout-probe;
writes the committed report to docs/reports/ and the contact sheet to /tmp.

Inputs:
  /tmp/layout-probe/png/<id>.swiftui.png           (SwiftUI, ImageRenderer)
  /tmp/layout-probe/swifttui-png/<id>.swifttui.png (SwiftTUI, @_spi(Raster) seam)
  /tmp/layout-probe/results.csv                    (IoU ranking from diff.py)

Requires ImageMagick (/opt/homebrew/bin/magick).
"""
from __future__ import annotations

import argparse
import csv
import os
import subprocess

MAGICK = "/opt/homebrew/bin/magick"
FONT = "/System/Library/Fonts/Supplemental/Arial.ttf"


def magick(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run([MAGICK, *args], capture_output=True, text=True)


def load_iou(results_csv: str) -> dict[str, float]:
    if not os.path.exists(results_csv):
        return {}
    out: dict[str, float] = {}
    for row in csv.DictReader(open(results_csv)):
        try:
            out[row["id"]] = float(row.get("iou", "") or "nan")
        except ValueError:
            pass
    return out


def build(probe_dir: str, out_report: str, contact_sheet: str, top: int) -> None:
    ui_dir = os.path.join(probe_dir, "png")
    tui_dir = os.path.join(probe_dir, "swifttui-png")
    work = os.path.join(probe_dir, "pixel")
    os.makedirs(work, exist_ok=True)
    iou = load_iou(os.path.join(probe_dir, "results.csv"))

    ids = sorted(
        f[: -len(".swifttui.png")]
        for f in os.listdir(tui_dir)
        if f.endswith(".swifttui.png")
    )

    pairs = []
    for id_ in ids:
        ui = os.path.join(ui_dir, f"{id_}.swiftui.png")
        tui = os.path.join(tui_dir, f"{id_}.swifttui.png")
        if not (os.path.exists(ui) and os.path.exists(tui)):
            continue
        score = iou.get(id_)
        label = f"{id_}    IoU={score:.2f}" if score is not None else id_
        pair = os.path.join(work, f"{id_}.pair.png")
        # SwiftUI (left) | SwiftTUI (right), natural aspect, labelled.
        magick("montage", ui, tui, "-tile", "2x1", "-geometry", "440x440+8+8",
               "-background", "#1b1b1b", "-fill", "#e8e8e8", "-font", FONT,
               "-pointsize", "16", "-title", label, pair)
        pairs.append({"id": id_, "iou": score, "pair": pair})

    # Worst extent-overlap first (lowest IoU); unknown IoU sinks to the end.
    ranked = sorted(pairs, key=lambda p: (p["iou"] is None, p["iou"] if p["iou"] is not None else 1.0))

    tiles = [p["pair"] for p in ranked[:top] if os.path.exists(p["pair"])]
    if tiles:
        magick("montage", *tiles, "-tile", "1x", "-geometry", "+0+12",
               "-background", "#000000", contact_sheet)

    L = ["# Layout comparison — true-pixel visual tier\n"]
    L.append("- **Date:** 2026-06-21")
    L.append(
        f"- **Entries:** {len(pairs)}  ·  SwiftUI `ImageRenderer` vs SwiftTUI "
        "`@_spi(Raster)` offscreen renders (both headless)")
    L.append("- **Generated by:** `tools/layout-diff/pixel_compare.py`. Auto-generated; re-run to refresh.")
    L.append(f"- **Contact sheet (worst {top} by IoU):** `{contact_sheet}`")
    L.append("")
    L.append("## What this is\n")
    L.append(
        "Side-by-side **SwiftUI (left) vs SwiftTUI (right)** renders of every "
        "comparison entry, ranked by the geometry content-extent IoU from "
        "`diff.py`. This is the human/LLM review surface that pairs with the "
        "numeric geometry tier.")
    L.append("")
    L.append(
        "> **No pixel-diff metric is reported.** DSSIM/AE between these engines "
        "saturate — proportional ink (SwiftUI, square cells) vs monospace glyphs "
        "(SwiftTUI, tall cells) means a force-resized pair is ~maximally "
        "different for every entry (the heatmap is ~all-red). That was measured "
        "and discarded; ranking uses the geometry IoU instead.")
    L.append("")
    L.append("## Per-entry pairs (worst extent-overlap first)\n")
    L.append("| IoU | id | pair image |")
    L.append("|---:|:--|:--|")
    for p in ranked:
        s = "—" if p["iou"] is None else f"{p['iou']:.2f}"
        L.append(f"| {s} | `{p['id']}` | `{p['pair']}` |")
    L.append("")
    os.makedirs(os.path.dirname(out_report), exist_ok=True)
    with open(out_report, "w") as f:
        f.write("\n".join(L))

    print(f"pixel tier: {len(pairs)} side-by-side pairs")
    print(f"contact sheet: {contact_sheet}")
    print(f"report: {out_report}")


def main() -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(os.path.dirname(here))
    p = argparse.ArgumentParser()
    p.add_argument("--probe-dir", default="/tmp/layout-probe")
    p.add_argument("--out", default=os.path.join(root, "docs/reports/2026-06-21-layout-comparison-pixel-sweep.md"))
    p.add_argument("--contact-sheet", default="/tmp/layout-probe/contact-sheet.png")
    p.add_argument("--top", type=int, default=12)
    args = p.parse_args()
    build(args.probe_dir, args.out, args.contact_sheet, args.top)


if __name__ == "__main__":
    main()
